// ─── Domain Types: NeuroLink Ideensammler ──────────────────────────

/** Eindeutige ID (UUID v4) */
export type UUID = string

/** Unix-Zeitstempel in Millisekunden */
export type Timestamp = number

/** Monoton steigende Version für Last-Write-Wins Sync */
export type SyncVersion = number

// ─── Idee ──────────────────────────────────────────────────────────

export type IdeaColor = string // Hex-Code

export interface Idea {
  id: UUID
  title: string
  content: string // Markdown / TipTap JSON
  color: IdeaColor
  posX: number
  posY: number
  clusterId: UUID | null
  createdAt: Timestamp
  updatedAt: Timestamp
  deletedAt: Timestamp | null // soft delete (Tombstone)
  syncVersion: SyncVersion
}

/** Teilmenge von Idea für die Erstellung (Server generiert fehlende Felder) */
export interface IdeaInput {
  title: string
  content?: string
  color?: IdeaColor
  posX?: number
  posY?: number
  clusterId?: UUID | null
}

/** Update-Payload — alle Felder optional, nur geänderte werden gesendet */
export interface IdeaUpdate {
  title?: string
  content?: string
  color?: IdeaColor
  posX?: number
  posY?: number
  clusterId?: UUID | null
}

// ─── Connection (gerichtete Kante / Synapse) ───────────────────────

export type ConnectionType =
  | 'associates'
  | 'extends'
  | 'contradicts'
  | 'inspires'
  | 'refines'
  | 'custom'

export interface Connection {
  id: UUID
  sourceId: UUID
  targetId: UUID
  type: ConnectionType
  weight: number // 0.0 – 1.0
  label: string | null
  createdAt: Timestamp
  updatedAt: Timestamp
  syncVersion: SyncVersion
}

export interface ConnectionInput {
  sourceId: UUID
  targetId: UUID
  type: ConnectionType
  weight?: number
  label?: string | null
}

export interface ConnectionUpdate {
  type?: ConnectionType
  weight?: number
  label?: string | null
}

// ─── Tag ───────────────────────────────────────────────────────────

export interface Tag {
  id: UUID
  name: string
  color: string | null
  createdAt: Timestamp
}

export interface IdeaTag {
  ideaId: UUID
  tagId: UUID
}

// ─── Cluster ───────────────────────────────────────────────────────

export interface Cluster {
  id: UUID
  name: string
  color: string | null
  autoGenerated: boolean
  createdAt: Timestamp
}

// ─── Sync Meta ────────────────────────────────────────────────────

export interface SyncMeta {
  deviceId: string
  lastSyncAt: Timestamp | null
  lastVersion: SyncVersion
  cursorToken: string | null
}

// ─── Aggregate Roots für UI ────────────────────────────────────────

export interface IdeaWithRelations extends Idea {
  tags: Tag[]
  connections: Connection[]
  cluster: Cluster | null
}

/** Der gesamte Graph — geladen vom Store für das Canvas */
export interface IdeaGraph {
  ideas: Idea[]
  connections: Connection[]
  tags: Tag[]
  clusters: Cluster[]
}
